
title: lrvu's site
email: 1209357309@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my site, there are some bolgs about my study and life.\n
  I'm lrvu, this nickname means 'love you~'.\n
  I am a noob in all round, 
  wish you have a good day when you see this description:)
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
twitter_userlink: 
github_username:  lrvu

# Build settings
# theme: jekyll-theme-cayman
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
